# Generated by Django 5.0.7 on 2024-08-03 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
